### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by 1600012423** [caslabai/yolov3tiny_tensorflow_int8_quantized#2]
Something happened when I ran "demo.py". The shape of variable "detection" is (1, 2535, 85), that's not reasonable. The error looks like this below:

Traceback (most recent call last):
  File "C:/projects/GitProjects/yolov3tiny_tensorflow_int8_quantized/demo.py", line 128, in <module>
    tf.app.run()
  File "F:\softwares\Anaconda\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:/projects/GitProjects/yolov3tiny_tensorflow_int8_quantized/demo.py", line 122, in main
    yolo_full()
  File "C:/projects/GitProjects/yolov3tiny_tensorflow_int8_quantized/demo.py", line 113, in yolo_full
    iou_threshold=FLAGS.iou_threshold)
  File "C:\projects\GitProjects\yolov3tiny_tensorflow_int8_quantized\utils.py", line 139, in non_max_suppression
    image_pred = image_pred.reshape(-1, shape[-1])
ValueError: cannot reshape array of size 1556 into shape (85)

**Comment by 1600012423** [comment]
I solved this. In "utils.py", line 135 should be corrected to be " non_zero_idxs = np.nonzero(image_pred[:, 5])".
